[module/cpu-usage]
inherit = module-base
type = internal/cpu
interval = 1
format-prefix = " "
format-prefix-foreground = ${colors.primary}
format-foreground = ${colors.foreground}
label = "%percentage:1%%"
click-left = kitty --config ~/.config/kitty/padding.conf --execute btop

[module/cpu-memory]
inherit = module-base
type = internal/memory
interval = 1
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = "%used:2%"
format-foreground = ${colors.foreground}

[module/cpu-temp-only]
inherit = module/cpu-temperature
format-prefix = "  "

[module/cpu-power]
inherit = module-base
format-foreground=${colors.foreground}
type = custom/script
format = <label>
format-prefix="󱄈  "
label = %output:1% W
#exec = fish --no-config -c "sudo s-tui -j | grep \"package-0,0\" | string replace -a ' ' '' | string replace -a '\"' '' | string replace -a ',' '' | string replace 'package-00:' ''"
format-prefix-foreground = ${colors.primary}
format-background = ${colors.background}
interval = 1
