background #1b1110
foreground #f3dedc
color0  #1b1110
color1  #ffb4ab
color2  #ffb3b0
color3  #78d8b5
color4  #feb4b0
color5  #6f3a38
color6  #007c5e
color7  #f3dedc
color8  #a58a89
color9  #93000a
color10 #b94647
color11 #78d8b5
color12 #feb4b0
color13 #ffdcda
color14 #ffffff
color15 #f3dedc
