background #15121a
foreground #e7e0eb
color0  #15121a
color1  #ffb4ab
color2  #84d7af
color3  #d5bcf4
color4  #e1bbdc
color5  #5a3d59
color6  #513e6d
color7  #e7e0eb
color8  #958e9e
color9  #93000a
color10 #005138
color11 #d5bcf4
color12 #e1bbdc
color13 #fed6f9
color14 #eddcff
color15 #e7e0eb
